### PR TITLE
Quadratic calculator is created

### PR DESCRIPTION
**Pull request by SOUMOJIT-CHAKRABORTY**
all set

### CODE REVIEW

**Comment by davejane25** [comment]
Good job @SOUMOJIT-CHAKRABORTY 👍  follow @davejane25 and contribute more!!

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
Hey! @davejane25 you merged the pull request but on hactoberfest website it's showing 'waiting'.
Do you know the reason?

**Comment by davejane25** [comment]
yes.. it will undergo 7 day quality test after that it'll show accepted
image

**Comment by SOUMOJIT-CHAKRABORTY** [comment]
Yes I just noticed that😂, Btw thanks a lot😊

**Pull request merged**
